services:
  blog:
    image: esanchezdevel/programandoconjava:{BLOG_VERSION}
    container_name: programandoconjava
    restart: always
    ports:
      - "8080:3500"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/programandoconjava
      - SPRING_DATASOURCE_USERNAME={DB_USER}
      - SPRING_DATASOURCE_PASSWORD={DB_PASS}
      - SPRING_PROFILE=dev
      - SPRING_PAYPAL_CLIENT_ID={PAYPAL_CLIENT_ID}
      - SPRING_PAYPAL_CLIENT_SECRET={PAYPAL_CLIENT_SECRET}
      - SPRING_MAIL_HOST={MAIL_HOST}
      - SPRING_MAIL_PORT={MAIL_PORT}
      - SPRING_MAIL_USERNAME={MAIL_USER}
      - SPRING_MAIL_PASSWORD={MAIL_PASS}
    volumes:
      - /var/opt/programandoconjava/products:/var/opt/programandoconjava/products
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER={DB_USER}
      - POSTGRES_PASSWORD={DB_PASS}
      - POSTGRES_DB=programandoconjava
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: