spring:
  application:
    name: programandoconjava

  datasource:
    url: jdbc:postgresql://postgres-headless.programandoconjava.svc.cluster.local:5432/programandoconjava
    username: admin
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          from: ${SPRING_MAIL_USERNAME}
          auth: true
          starttls:
            enable: true


server:
  port: 3500
  error:
    whitelable:
      enabled: false

payments:
  paypal:
    client-id: ${SPRING_PAYPAL_CLIENT_ID}
    client-secret: ${SPRING_PAYPAL_CLIENT_SECRET}